publiclab/infragram

- index.html
> open links in new tabs

- README.md
> Added information for contribution

- README.md
- package-lock.json
> Added installation in README

- index.html
@publiclab/reviewers  Please review This
Fixes #87
> Fixing the upload an image button not working 

- .github/workflows/tests.yml
* Create ci.yml
This commit is to migrate checks from TravisCI to GitHub Actions
* Update ci.yml
* Update and rename ci.yml to tests.yml
* Update tests.yml
* Update tests.yml
* Update tests.yml
* Update tests.yml
* Update tests.yml
Co-authored-by: Govind Goel <52847415+govindgoel@users.noreply.github.com>
> Create ci.yml for github actions (renamed tests.yml) (#156)

- index.html
[Added extra explanation to Presets menu #180 ](https://github.com/publiclab/infragram/issues/180)
-               <p>Choose from these presets to get up and running quickly:</p>
+               <p>Choose from these presets to get up and running quickly. These auto-load common 2. Analysis and 3. Colorize settings so you don't have to manually choose them.</p>
please checkout my pull request
> Fixes (#180) Added extra explanation to Presets menu

- dist/infragram.css
- package-lock.json
Fixes #192
**Description**
For a user, it's nice to have a 'pointer' cursor when hovering over, so that it makes it really clear that they should click it.
**Type of Change:**
- Code
- User Interface
> Add cursor property

- index.html
> fixed tooltip message

- index.html
> Favicon is added #193

- index.html
Solution to issue 224 assigned to me - https://github.com/publiclab/infragram/issues/224
> Change ANALYZE to CONVERT/ANALYZE in help text

- .github/first-timers-issue-template.md
> First timer issue template added from Plot2 repo

- .github/config.yml
Found a small typo in  .github/config.yml
> Fixed typos in .github/config.yml

- dist/infragram.css
- index.html
moved the style rule from index.html into infragram.cs
s
> moved style tag rule into infragram.css

- dist/infragram.css
This fixes issue https://github.com/publiclab/infragram/issues/286
> Added quotes to font-names containing whitespaces

- index.html
> Hide grid overlay controls on initial display 

- dist/infragram.js
- src/io/camera.js
- src/ui/interface.js
solves #289 
Removed the unnecessary logs.
> removed unecessary logs

- README.md
> aligned images to center

- README.md
fixes #325 
Added the link of tutorial for creating a PULL REQUEST.
> Added link of tutorial for creating a PULL REQUEST

- dist/infragram.css
@TildaDares @jywarren I tried to make this a first-timers issue but there was no branch option at the bottom. Can you guide me on this?
> Missing semi-colon in infragram.css

- README.md
Updates the encouraging message on line 221 to be bolded (**). 
Fixes #407
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
> added bolded encouraging message

- vr/index.html
Fixes #474  
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
> fix: removed empty paragragh tag and irrelevant files
